In [1]:
import numpy as np
import pprint as pp
from IPython.display import display
import tabulate

# Original data

In [2]:
N = 4
steps = 5
adata = np.arange(N * steps).reshape(N, steps)

in_one = np.array([1, 1, 0, 0])
in_two = np.array([0, 0, 0, 1])
in_three = np.array([1, 0, 0, 0])

# Produce conversion matrix

In [3]:
needed_mask = in_one | in_two | in_three
N_sim = sum(needed_mask)
J = np.arange(N_sim * N_sim).reshape(N_sim, N_sim)
needed_mask = needed_mask.astype(np.bool)
collapse_convert = np.eye(N, dtype=np.bool)[..., needed_mask]

In [4]:
display(needed_mask)

array([ True,  True, False,  True])

In [5]:
display(collapse_convert)

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False,  True]])

# Apply conversions

In [6]:
collapsed = adata[needed_mask,...]

In [7]:
sim_in_one = in_one @ collapse_convert
sim_in_one = sim_in_one.astype(np.bool)
table = []
table.append(['in_one', pp.pformat(in_one)])
table.append(['sim_in_one', pp.pformat(sim_in_one)])
table.append(['collapsed[sim_in_one, ...]', pp.pformat(collapsed[sim_in_one, ...])])
print(tabulate.tabulate(table))

--------------------------  ----------------------------
in_one                      array([1, 1, 0, 0])
sim_in_one                  array([ True,  True, False])
collapsed[sim_in_one, ...]  array([[0, 1, 2, 3, 4],
                                   [5, 6, 7, 8, 9]])
--------------------------  ----------------------------


In [8]:
sim_in_two = in_two @ collapse_convert
sim_in_two = sim_in_two.astype(np.bool)
table = []
table.append(['in_two', pp.pformat(in_two)])
table.append(['sim_in_two', pp.pformat(sim_in_two)])
table.append(['collapsed[sim_in_two, ...]', pp.pformat(collapsed[sim_in_two, ...])])
print(tabulate.tabulate(table))

--------------------------  -----------------------------
in_two                      array([0, 0, 0, 1])
sim_in_two                  array([False, False,  True])
collapsed[sim_in_two, ...]  array([[15, 16, 17, 18, 19]])
--------------------------  -----------------------------


In [9]:
sim_in_three = in_three @ collapse_convert
sim_in_three = sim_in_three.astype(np.bool)
table = []
table.append(['in_three', pp.pformat(in_three)])
table.append(['sim_in_three', pp.pformat(sim_in_three)])
table.append(['collapsed[sim_in_three, ...]', pp.pformat(collapsed[sim_in_three, ...])])
print(tabulate.tabulate(table))

----------------------------  ----------------------------
in_three                      array([1, 0, 0, 0])
sim_in_three                  array([ True, False, False])
collapsed[sim_in_three, ...]  array([[0, 1, 2, 3, 4]])
----------------------------  ----------------------------


# Extracting weights

This may look different in matlab, but the methods should be similar

In [10]:
display(J)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Input weights to sim_in_one units

In [11]:
display(J[sim_in_one, ...])

array([[0, 1, 2],
       [3, 4, 5]])

### Output weights from sim_in_one units

In [12]:
display(J[..., sim_in_one])

array([[0, 1],
       [3, 4],
       [6, 7]])

### Output weights from sim_in_one units to sim_in_two units

In [13]:
display(J[..., sim_in_one][sim_in_two,...])

array([[6, 7]])

### Input weights to sim_in_one units from sim_in_two units

In [14]:
display(J[sim_in_one, ...][..., sim_in_two])

array([[2],
       [5]])